const js = require('@eslint/js');
const globals = require('globals');

const srcGlobals = {
  ...globals.browser,
  chrome: 'readonly',
  globalThis: 'readonly',
  AIStore: 'readonly',
  AIService: 'readonly',
  AIRenderer: 'readonly',
  MarkdownParser: 'readonly',
  OpenRouterAPI: 'readonly',
  OfflineMode: 'readonly',
  NetworkDetector: 'readonly',
  AppGridState: 'readonly',
  AppGridStorage: 'readonly',
  AppFolders: 'readonly',
  defaultApps: 'readonly',
  VisibilityInterval: 'readonly',
  visibilityManager: 'readonly',
  validateUrl: 'readonly',
  isValidUrl: 'readonly',
  isMalformedUrl: 'readonly',
  isSearchQuery: 'readonly',
  normalizeUrl: 'readonly',
  iconCache: 'readonly',
  onDomReady: 'readonly',
  initModernFontPickers: 'readonly',
  ModernFontPicker: 'readonly',
  initModernColorPickers: 'readonly',
  ModernColorPicker: 'readonly',
  __appGridState: 'readonly',
  renderCustomApps: 'readonly',
  renderAllApps: 'readonly',
  initAddAppModal: 'readonly',
  renderDefaultAppsList: 'readonly',
  closeAddAppModal: 'readonly',
  updateAddAppPreview: 'readonly',
  openAddAppModal: 'readonly',
  applySimpleMode: 'readonly',
  loadSimpleMode: 'readonly',
  applyFocusMode: 'readonly',
  loadFocusMode: 'readonly',
  setFocusMode: 'readonly',
  toggleFocusMode: 'readonly',
  updateTime: 'readonly',
  checkFooterOverlap: 'readonly',
  onboardingTour: 'readonly',
  renameAppId: 'readonly',
  thumbnailAppId: 'readonly',
  deleteAppId: 'readonly',
  updateChecker: 'readonly',
  i18n: 'readonly',
  CURRENT_VERSION: 'readonly',
  VERSION_DISPLAY_UNAVAILABLE_TEXT: 'readonly',
  _backgrounds: 'readonly',
  _initStaticBackgrounds: 'readonly',
  _initLiveBackgrounds: 'readonly',
  _initInteractiveBackgrounds: 'readonly',
  _findBackgroundUrlById: 'readonly',
  _isVideoBackground: 'readonly',
  _getStaticBackgrounds: 'readonly',
  _getVideoBackgrounds: 'readonly',
  _getInteractiveBackgrounds: 'readonly',
  applyBg: 'readonly',
  captureBackgroundSnapshot: 'readonly',
  hideBackgroundOverlay: 'readonly',
  loadVideoAutoplay: 'readonly',
  loadVideoMuted: 'readonly',
  mottos: 'readonly',
  parseLocalDate: 'readonly',
  scheduleTodoReminderCheck: 'readonly',
  loadEyeCareReminderState: 'readonly',
  saveEyeCareReminderState: 'readonly',
  applyEyeCareReminderSettings: 'readonly',
  refreshEyeCareReminder: 'readonly',
  translateValidationMessage: 'readonly',
  showToast: 'readonly',
  safePause: 'readonly',
  safeLoad: 'readonly',
  crossfadeDelayMs: 'readonly',
  BackgroundRotation: 'readonly',
  currentFilters: 'readonly',
  getSelectedPriority: 'readonly',
  Shortcuts: 'readonly',
  applyTodoEnabled: 'readonly',
  applyNotesEnabled: 'readonly',
  WeatherApp: 'readonly',
  addSubtask: 'readonly',
  deleteSubtask: 'readonly',
  toggleSubtask: 'readonly',
  updateSubtaskText: 'readonly',
  getSubtaskProgress: 'readonly',
  cloneTodos: 'readonly',
  renderTodos: 'readonly',
  editModalState: 'readonly',
  openEditModal: 'readonly',
  saveEdit: 'readonly',
  closeEditModal: 'readonly',
  loadTodoStats: 'readonly',
  saveTodoStats: 'readonly',
  recordTodoCompletion: 'readonly',
  clearTodoStats: 'readonly',
  applyTodoStatsVisibility: 'readonly',
  renderTodoStats: 'readonly',
  loadTodoStatsEnabled: 'readonly',
  getCompletedToday: 'readonly',
  getCompletedThisWeek: 'readonly',
  module: 'readonly',
  exports: 'readonly',
  BUILT_IN_PROVIDERS: 'readonly',
  loadActiveProvider: 'readonly',
  saveActiveProvider: 'readonly',
  loadCustomProviders: 'readonly',
  saveCustomProviders: 'readonly',
  addCustomProvider: 'readonly',
  removeCustomProvider: 'readonly',
  getAllProviders: 'readonly',
  getActiveProviderUrl: 'readonly',
  updateProviderSelection: 'readonly',
};

const testGlobals = {
  ...globals.browser,
  ...globals.node,
  chrome: 'readonly',
  AppGridStorage: 'readonly',
  AppGridState: 'readonly',
  __appGridState: 'readonly',
  AIStore: 'readonly',
  AIService: 'readonly',
  AIRenderer: 'readonly',
  OpenRouterAPI: 'readonly',
  OfflineMode: 'readonly',
  NetworkDetector: 'readonly',
  MarkdownParser: 'readonly',
  iconCache: 'readonly',
  VisibilityInterval: 'readonly',
  visibilityManager: 'readonly',
  validateUrl: 'readonly',
  isValidUrl: 'readonly',
  isMalformedUrl: 'readonly',
  isSearchQuery: 'readonly',
  normalizeUrl: 'readonly',
  translateValidationMessage: 'readonly',
  formatClockTime: 'readonly',
  getClockFormat: 'readonly',
  formatDateDisplay: 'readonly',
  getDateFormat: 'readonly',
  getDisplayLocale: 'readonly',
  recordSearchHistory: 'readonly',
  runSearch: 'readonly',
  selectSearchHistorySuggestion: 'readonly',
  showSearchValidationFeedback: 'readonly',
  loadBg: 'readonly',
  loadClockStyle: 'readonly',
  loadDateStyle: 'readonly',
  loadTheme: 'readonly',
  loadTodoEnabled: 'readonly',
  loadEyeCareReminderState: 'readonly',
  saveEyeCareReminderState: 'readonly',
  applyEyeCareReminderSettings: 'readonly',
  refreshEyeCareReminder: 'readonly',
  loadFocusMode: 'readonly',
  loadClockFormatSetting: 'readonly',
  loadDateFormatSetting: 'readonly',
  getClosestSettingSize: 'readonly',
  applyBg: 'readonly',
  captureBackgroundSnapshot: 'readonly',
  hideBackgroundOverlay: 'readonly',
  clearBackgroundTransitionTimeout: 'readonly',
  loadLanguageSetting: 'readonly',
  renderLanguageOptions: 'readonly',
  initModernFontPickers: 'readonly',
  initModernColorPickers: 'readonly',
  loadVideoAutoplay: 'readonly',
  loadVideoMuted: 'readonly',
  crossfadeDelayMs: 'readonly',
  loadVideoPauseHidden: 'readonly',
  applyVideoPlaybackSettings: 'readonly',
  applyFocusMode: 'readonly',
  setFocusMode: 'readonly',
  toggleFocusMode: 'readonly',
  BackgroundRotation: 'readonly',
  initTodo: 'readonly',
  loadTodos: 'readonly',
  saveTodos: 'readonly',
  addTodo: 'readonly',
  editTodo: 'readonly',
  toggleTodo: 'readonly',
  deleteTodo: 'readonly',
  migrateTodos: 'readonly',
  handleFilterPillClick: 'readonly',
  filterTodos: 'readonly',
  currentFilters: 'readonly',
  getSelectedPriority: 'readonly',
  formatDateISO: 'readonly',
  isOverdue: 'readonly',
  parseLocalDate: 'readonly',
  AppGridState: 'readonly',
  AppFolders: 'readonly',
  defaultApps: 'readonly',
  clearCompleted: 'readonly',
  validateTodoData: 'readonly',
  showImportDialog: 'readonly',
  handleDrop: 'readonly',
  handleDragStart: 'readonly',
  handleDragEnd: 'readonly',
  scheduleTodoReminderCheck: 'readonly',
  addSubtask: 'readonly',
  deleteSubtask: 'readonly',
  toggleSubtask: 'readonly',
  updateSubtaskText: 'readonly',
  getSubtaskProgress: 'readonly',
  cloneTodos: 'readonly',
  renderTodos: 'readonly',
  editModalState: 'readonly',
  openEditModal: 'readonly',
  saveEdit: 'readonly',
  closeEditModal: 'readonly',
  loadTodoStats: 'readonly',
  saveTodoStats: 'readonly',
  recordTodoCompletion: 'readonly',
  clearTodoStats: 'readonly',
  applyTodoStatsVisibility: 'readonly',
  renderTodoStats: 'readonly',
  loadTodoStatsEnabled: 'readonly',
  getCompletedToday: 'readonly',
  getCompletedThisWeek: 'readonly',
  checkReminders: 'readonly',
  handleStartup: 'readonly',
  initNotes: 'readonly',
  addNote: 'readonly',
  deleteNote: 'readonly',
  updateNoteText: 'readonly',
  updateNoteTag: 'readonly',
  reorderNotes: 'readonly',
  Shortcuts: 'readonly',
  applyTodoEnabled: 'readonly',
  applyNotesEnabled: 'readonly',
  WeatherApp: 'readonly',
  describe: 'readonly',
  it: 'readonly',
  test: 'readonly',
  expect: 'readonly',
  vi: 'readonly',
  initModernFontPickers: 'readonly',
  initModernColorPickers: 'readonly',
  beforeAll: 'readonly',
  beforeEach: 'readonly',
  afterEach: 'readonly',
  afterAll: 'readonly',
  BUILT_IN_PROVIDERS: 'readonly',
  loadActiveProvider: 'readonly',
  saveActiveProvider: 'readonly',
  loadCustomProviders: 'readonly',
  saveCustomProviders: 'readonly',
  addCustomProvider: 'readonly',
  removeCustomProvider: 'readonly',
  getAllProviders: 'readonly',
  getActiveProviderUrl: 'readonly',
  updateProviderSelection: 'readonly',
};

const commonRules = {
  semi: ['error', 'always'],
  quotes: ['error', 'single'],
  eqeqeq: ['error', 'always'],
  'no-var': 'error',
  'prefer-const': 'warn',
  camelcase: ['warn', { properties: 'never' }],
  'no-console': ['warn', { allow: ['info', 'log', 'warn', 'error'] }],
  'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
  'preserve-caught-error': 'off',
};

module.exports = [
  {
    ignores: ['coverage/**', 'node_modules/**', 'eslint.config.js'],
  },
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: srcGlobals,
    },
    rules: {
      ...commonRules,
      'no-redeclare': 'off',
    },
  },
  // Files wrapped in strict-mode IIFEs must reference globals via window.*
  // to avoid ReferenceErrors from bare identifiers. This list includes all
  // IIFE-wrapped source files: add-app-modal, context-menu, app-manager,
  // app-folders, drag-drop, and utils.
  {
    files: [
      'src/ui/add-app-modal.js',
      'src/features/context-menu.js',
      'src/ui/app-manager.js',
      'src/features/app-folders.js',
      'src/features/drag-drop.js',
      'src/core/utils.js'
    ],
    languageOptions: {
      sourceType: 'script',
      globals: srcGlobals,
    },
    rules: {
      ...commonRules,
      'no-redeclare': 'off',
      'no-restricted-globals': ['error', {
        name: 'AppGridState',
        message: 'Use window.AppGridState instead to avoid ReferenceErrors in strict-mode IIFEs.',
      }, {
        name: 'escapeHtml',
        message: 'Capture as `const escapeHtml = window.escapeHtml;` at the top of the IIFE to avoid ReferenceErrors.',
      }],
    },
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      sourceType: 'module',
      globals: testGlobals,
    },
    rules: {
      ...commonRules,
    },
  },
  {
    files: ['background/tools/**/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      ...commonRules,
      'no-redeclare': 'off',
      'no-console': 'off',
    },
  },
  {
    files: ['background/service-worker.js', 'background/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        ...globals.browser,
        chrome: 'readonly',
      },
    },
    rules: {
      ...commonRules,
    },
  },
];
