import globals from "globals";

export default [
  {
    ignores: ["background/", "coverage/", "node_modules/"],
  },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        chrome: "readonly",
        // Cross-file globals — defined by other source scripts in the HTML load order
        AIStore: "writable",
        AIRenderer: "writable",
        AIService: "writable",
        NetworkDetector: "writable",
        OfflineMode: "writable",
        OpenRouterAPI: "writable",
        MarkdownParser: "writable",
        AppGridState: "writable",
        AppGridStorage: "writable",
        VisibilityInterval: "writable",
        mottos: "writable",
        backgrounds: "writable",
        customBackgroundManager: "writable",
        CURRENT_VERSION: "writable",
        i18n: "writable",
        escapeHtml: "writable",
        t: "writable",
        showToast: "writable",
        validateUrl: "writable",
        translateValidationMessage: "writable",
        updateTime: "writable",
        updateChecker: "writable",
        applyBg: "writable",
        onboardingTour: "writable",
        OnboardingTour: "writable",
        UpdateChecker: "writable",
        CustomDatePicker: "writable",
        ModernFontPicker: "writable",
        ModernColorPicker: "writable",
        LRUCache: "writable",
        dragData: "writable",
        draggedElement: "writable",
        renameAppId: "writable",
        thumbnailAppId: "writable",
        deleteAppId: "writable",
      },
    },
    rules: {
      semi: "error",
      quotes: ["error", "single", { avoidEscape: true }],
      indent: ["error", 2, { SwitchCase: 1 }],
      eqeqeq: "error",
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-undef": "warn",
      "no-var": "warn",
      "prefer-const": "warn",
      "no-dupe-keys": "error",
      "no-redeclare": ["error", { builtinGlobals: false }],
      "no-unreachable": "error",
      "no-fallthrough": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-semi": "error",
      "comma-dangle": "off",
      strict: "off",
    },
  },
  {
    files: ["tests/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        vi: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
      },
    },
  },
];
