const js = require('@eslint/js');
const globals = require('globals');

const srcGlobals = {
  ...globals.browser,
  chrome: 'readonly',
  globalThis: 'readonly',
  AIStore: 'readonly',
  AIService: 'readonly',
  AIRenderer: 'readonly',
  MarkdownParser: 'readonly',
  OpenRouterAPI: 'readonly',
  OfflineMode: 'readonly',
  NetworkDetector: 'readonly',
  AppGridState: 'readonly',
  AppGridStorage: 'readonly',
  VisibilityInterval: 'readonly',
  visibilityManager: 'readonly',
  validateUrl: 'readonly',
  isValidUrl: 'readonly',
  isMalformedUrl: 'readonly',
  isSearchQuery: 'readonly',
  normalizeUrl: 'readonly',
  iconCache: 'readonly',
  onDomReady: 'readonly',
  initModernFontPickers: 'readonly',
  ModernFontPicker: 'readonly',
  initModernColorPickers: 'readonly',
  ModernColorPicker: 'readonly',
  appGridReady: 'readonly',
  renderCustomApps: 'readonly',
  renderAllApps: 'readonly',
  initAddAppModal: 'readonly',
  renderDefaultAppsList: 'readonly',
  closeAddAppModal: 'readonly',
  updateAddAppPreview: 'readonly',
  openAddAppModal: 'readonly',
  applySimpleMode: 'readonly',
  loadSimpleMode: 'readonly',
  updateTime: 'readonly',
  checkFooterOverlap: 'readonly',
  onboardingTour: 'readonly',
  renameAppId: 'readonly',
  thumbnailAppId: 'readonly',
  deleteAppId: 'readonly',
  updateChecker: 'readonly',
  i18n: 'readonly',
  CURRENT_VERSION: 'readonly',
  VERSION_DISPLAY_UNAVAILABLE_TEXT: 'readonly',
  _backgrounds: 'readonly',
  _initBackgrounds: 'readonly',
  _initStaticBackgrounds: 'readonly',
  _initLiveBackgrounds: 'readonly',
  _initInteractiveBackgrounds: 'readonly',
  _findBackgroundUrlById: 'readonly',
  _isVideoBackground: 'readonly',
  _getStaticBackgrounds: 'readonly',
  _getVideoBackgrounds: 'readonly',
  _getInteractiveBackgrounds: 'readonly',
  applyBg: 'readonly',
  mottos: 'readonly',
  translateValidationMessage: 'readonly',
  showToast: 'readonly',
  module: 'readonly',
  exports: 'readonly',
};

const testGlobals = {
  ...globals.browser,
  ...globals.node,
  chrome: 'readonly',
  AppGridStorage: 'readonly',
  AppGridState: 'readonly',
  MarkdownParser: 'readonly',
  iconCache: 'readonly',
  validateUrl: 'readonly',
  isValidUrl: 'readonly',
  isMalformedUrl: 'readonly',
  isSearchQuery: 'readonly',
  normalizeUrl: 'readonly',
  translateValidationMessage: 'readonly',
  formatClockTime: 'readonly',
  getClockFormat: 'readonly',
  formatDateDisplay: 'readonly',
  getDateFormat: 'readonly',
  getDisplayLocale: 'readonly',
  recordSearchHistory: 'readonly',
  runSearch: 'readonly',
  loadBg: 'readonly',
  loadClockStyle: 'readonly',
  loadDateStyle: 'readonly',
  loadTheme: 'readonly',
  loadTodoEnabled: 'readonly',
  loadClockFormatSetting: 'readonly',
  loadDateFormatSetting: 'readonly',
  getClosestSize: 'readonly',
  applyBg: 'readonly',
  loadLanguageSetting: 'readonly',
  renderLanguageOptions: 'readonly',
  initModernFontPickers: 'readonly',
  initModernColorPickers: 'readonly',
  loadVideoAutoplay: 'readonly',
  loadVideoMuted: 'readonly',
  loadVideoPauseHidden: 'readonly',
  applyVideoPlaybackSettings: 'readonly',
  initTodo: 'readonly',
  loadTodos: 'readonly',
  saveTodos: 'readonly',
  addTodo: 'readonly',
  editTodo: 'readonly',
  toggleTodo: 'readonly',
  deleteTodo: 'readonly',
  migrateTodos: 'readonly',
  handleFilterPillClick: 'readonly',
  filterTodos: 'readonly',
  formatDateISO: 'readonly',
  isOverdue: 'readonly',
  clearCompleted: 'readonly',
  validateTodoData: 'readonly',
  showImportDialog: 'readonly',
  initNotes: 'readonly',
  loadNotes: 'readonly',
  saveNotes: 'readonly',
  addNote: 'readonly',
  deleteNote: 'readonly',
  updateNoteText: 'readonly',
  handleNotesBlur: 'readonly',
  debouncedSave: 'readonly',
  flushPendingSaves: 'readonly',
  describe: 'readonly',
  it: 'readonly',
  test: 'readonly',
  expect: 'readonly',
  vi: 'readonly',
  beforeAll: 'readonly',
  beforeEach: 'readonly',
  afterEach: 'readonly',
  afterAll: 'readonly',
};

const commonRules = {
  semi: ['error', 'always'],
  quotes: ['error', 'single'],
  eqeqeq: ['error', 'always'],
  'no-var': 'error',
  'prefer-const': 'warn',
  camelcase: ['warn', { properties: 'never' }],
  'no-console': ['warn', { allow: ['info', 'log', 'warn', 'error'] }],
  'no-unused-vars': ['warn', { args: 'none', varsIgnorePattern: '^_' }],
  'preserve-caught-error': 'off',
};

module.exports = [
  {
    ignores: ['coverage/**', 'node_modules/**', 'eslint.config.js'],
  },
  js.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: srcGlobals,
    },
    rules: {
      ...commonRules,
      'no-redeclare': 'off',
    },
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      sourceType: 'module',
      globals: testGlobals,
    },
    rules: {
      ...commonRules,
    },
  },
  {
    files: ['background/tools/**/*.js'],
    languageOptions: {
      sourceType: 'script',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      ...commonRules,
      'no-redeclare': 'off',
      'no-console': 'off',
    },
  },
];
