import globals from "globals";

export default [
  {
    ignores: ["coverage/", "node_modules/"],
  },
  {
    files: ["src/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        ...globals.browser,
        chrome: "readonly",
        // Cross-file globals — defined by other source scripts in the HTML load order
        module: "readonly",
        AIStore: "writable",
        AIRenderer: "writable",
        AIService: "writable",
        NetworkDetector: "writable",
        OfflineMode: "writable",
        OpenRouterAPI: "writable",
        MarkdownParser: "writable",
        AppGridState: "writable",
        AppGridStorage: "writable",
        VisibilityInterval: "writable",
        mottos: "writable",
        backgrounds: "writable",
        customBackgroundManager: "writable",
        CURRENT_VERSION: "writable",
        i18n: "writable",
        escapeHtml: "writable",
        t: "writable",
        showToast: "writable",
        validateUrl: "writable",
        translateValidationMessage: "writable",
        updateTime: "writable",
        updateChecker: "writable",
        applyBg: "writable",
        onboardingTour: "writable",
        OnboardingTour: "writable",
        UpdateChecker: "writable",
        CustomDatePicker: "writable",
        ModernFontPicker: "writable",
        ModernColorPicker: "writable",
        LRUCache: "writable",
        dragData: "writable",
        draggedElement: "writable",
        renameAppId: "writable",
        thumbnailAppId: "writable",
        deleteAppId: "writable",
      },
    },
    rules: {
      semi: "error",
      quotes: ["error", "single", { avoidEscape: true }],
      indent: ["error", 2, { SwitchCase: 1 }],
      eqeqeq: "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-var": "warn",
      "prefer-const": "error",
      "no-dupe-keys": "error",
      "no-redeclare": ["error", { builtinGlobals: false }],
      "no-unreachable": "error",
      "no-fallthrough": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-semi": "error",
      "comma-dangle": "off",
      strict: "off",
    },
  },
  {
    files: ["tests/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "module",
      globals: {
        ...globals.browser,
        // Vitest globals
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        vi: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        // Node.js (used by helpers/inject-script.js)
        process: "readonly",
        // Chrome API mock (setup.js)
        chrome: "readonly",
        // Cross-file globals defined by injected source scripts
        AppGridStorage: "writable",
        AppGridState: "writable",
        MarkdownParser: "writable",
        formatClockTime: "writable",
        getClockFormat: "writable",
        formatDateDisplay: "writable",
        getDateFormat: "writable",
        getDisplayLocale: "writable",
        loadBg: "writable",
        loadClockStyle: "writable",
        loadDateStyle: "writable",
        loadTheme: "writable",
        loadTodoEnabled: "writable",
        loadClockFormatSetting: "writable",
        loadDateFormatSetting: "writable",
        getClosestSize: "writable",
        applyBg: "writable",
        loadLanguageSetting: "writable",
        renderLanguageOptions: "writable",
        initTodo: "writable",
        loadTodos: "writable",
        saveTodos: "writable",
        addTodo: "writable",
        toggleTodo: "writable",
        editTodo: "writable",
        deleteTodo: "writable",
        handleFilterPillClick: "writable",
        filterTodos: "writable",
        formatDateISO: "writable",
        isOverdue: "writable",
        migrateTodos: "writable",
        clearCompleted: "writable",
        validateUrl: "writable",
        isValidUrl: "writable",
        isMalformedUrl: "writable",
        isSearchQuery: "writable",
        normalizeUrl: "writable",
        translateValidationMessage: "writable",
        iconCache: "writable",
      },
    },
    rules: {
      semi: "error",
      quotes: ["error", "single", { avoidEscape: true }],
      eqeqeq: "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "prefer-const": "error",
      "no-dupe-keys": "error",
      "no-unreachable": "error",
      "no-extra-semi": "error",
      "comma-dangle": "off",
    },
  },
  {
    files: ["background/tools/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "commonjs",
      globals: {
        ...globals.node,
      },
    },
    rules: {
      semi: "error",
      quotes: ["error", "single", { avoidEscape: true }],
      indent: ["error", 2, { SwitchCase: 1 }],
      eqeqeq: "error",
      "no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
      "no-undef": "error",
      "no-var": "warn",
      "prefer-const": "error",
      "no-dupe-keys": "error",
      "no-redeclare": ["error", { builtinGlobals: false }],
      "no-unreachable": "error",
      "no-fallthrough": "error",
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-extra-semi": "error",
      "comma-dangle": "off",
      strict: "off",
    },
  },
];
